name: Frontend Automate Deploy

on:

  push:
    branches: [ frontend ]
    paths: 
      - 'maid-care-service-frontend/**'

  workflow_dispatch:

defaults:
  run:
    working-directory: maid-care-service-frontend

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      
      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          noprefix: true
          title: "Merge!!"
          description: "Deploying Website"
          color: 0x6f42c1
          username: Werewolf GitHub Actions

      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with: 
          node-version: 14.x
            
      - name: Build the site
        run: |
          npm install --production 
          npm fund
          npm run build
      
      - name: Install Netlify
        run: sudo npm install -g netlify-cli --unsafe-perm=true
        
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.1.11
        with:

          publish-dir: './maid-care-service-frontend/build/'

          deploy-message: ${{ github.event.head_commit.message }}

          production-branch: frontend
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          
      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Deploy on Netlify"
          color: 0x28a745
          username: Werewolf GitHub Actions
      
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Deploy on Netlify"
          color: 0xd73a49
          username: Werewolf GitHub Actions
